#!/usr/bin/php
<?php
require __DIR__ . '/../lib/autoload.php';

$db = new Database();

$cmd = shell_exec("sudo iptables -nvxL FORWARD --line-numbers|awk 'NR>2{print $1 \"|\" $3 \"|\" $9 \"|\" $10}'");

if( empty($cmd) ) exit;

$data = explode("\n", trim($cmd));
$temp = [];

foreach($data as $d) {
  $a = explode("|", trim($d));
  $ip = NULL;

  $rulenum = $a[0];
  $mb_used = $a[1] / 1e6;

  $ip_src = $a[2];
  $ip_dst = $a[3];

  if( $mb_used == 0 ) continue;

  exec("sudo iptables -Z FORWARD {$rulenum}");

  if( strpos($ip_src,'10.0.') === 0 ) {
    $ip = $ip_src;
  }

  if( strpos($ip_dst,'10.0.') === 0 ) {
    $ip = $ip_dst;
  }

  array_push($temp, ['ip' => $ip, 'mb' => $mb_used]);
}

if( count($temp) == 0 ) exit;

foreach($temp as $d) {
  $ip = $d['ip'];
  $mb = $d['mb'];

  $db->mb_used = $mb;
  $db->ip_addr = $ip;

  if( $db->get_device_id_by_ip() == 0 ) {
    $ipt = new Iptables($ip);
    $ipt->rem_client();
    continue;
  }

  usleep(1e5);
  $db->set_mb_used();
  usleep(1e5);

  list($mb_limit,$mb_used) = $db->get_data_usage();
  echo "$ip: $mb; $mb_limit; $mb_used";

  if( $mb_limit <= $mb_used ) {
    $ipt = new Iptables($ip);
    $ipt->rem_client();
    echo "-disconnected";
  }
  echo "\n";
  sleep(1);
}

exit;
