#!/usr/bin/php
<?php
require __DIR__ . '/../lib/autoload.php';

$db = new Database();

$cmd = shell_exec("sudo iptables -nvxL FORWARD --line-numbers|awk 'NR>2{print $1 \"|\" $3 \"|\" $9 \"|\" $10}'");

if( empty($cmd) ) { sleep(10); exit; }

$data = explode("\n", trim($cmd));
$temp = [];

foreach($data as $d) {
  $a = explode("|", trim($d));
  $ip = '255.255.255.255';

  $rulenum = $a[0];
  $mb_used = $a[1] / 1e6;

  $ip_src = $a[2];
  $ip_dst = $a[3];

  if( $mb_used == 0 ) continue;

  exec("sudo iptables -Z FORWARD {$rulenum}");

  if( strpos($ip_src,'10.0') === 0 ) {
    $ip = $ip_src;
  }

  if( strpos($ip_dst,'10.0') === 0 ) {
    $ip = $ip_dst;
  }

  $temp[$ip] = $mb_used + (isset($temp[$ip]) ? $temp[$ip] : 0);
}

if( count($temp) == 0 ) { sleep(10); exit; }

$logfile = '/var/log/foswvs.log';

$fp = fopen($logfile, (@filesize($logfile)>1e6 ? 'w' : 'a'));

foreach($temp as $ip=>$mb) {
  $dt = date('Y-m-d H:i:s');

  $db->mb_used = $mb;
  $db->ip_addr = $ip;

  fwrite($fp, "$dt - get_device_id_by_ip_$ip $mb\n");

  if( !$db->get_device_id_by_ip() ) {
    fwrite($fp, "$dt - unregistered device $ip\n");
    $ipt = new Iptables($ip);
    $ipt->rem_client();
    continue;
  }

  $db->set_mb_used(); sleep(1);

  list($mb_limit,$mb_used) = $db->get_data_usage();

  if( $mb_limit <= $mb_used ) {
    $ipt = new Iptables($ip);
    $ipt->rem_client();
  }
}

fclose($fp);
exit;
