#!/usr/bin/php
<?php
require __DIR__ . '/../lib/autoload.php';

$ip = $argv[1];
$mac = $argv[2];
$host = $argv[3];

if( !filter_var($mac, FILTER_VALIDATE_MAC) ) {
  $mac = implode(':',array_map(function($s){return str_pad($s,2,'0',STR_PAD_LEFT);},explode(':',$mac)));
}

if( filter_var($ip, FILTER_VALIDATE_IP) && filter_var($mac, FILTER_VALIDATE_MAC) ) {
  $db = new Database();

  $db->set_ip($ip);
  $db->set_host($host);
  $db->set_mac(strtoupper($mac));

  if( !$db->get_device_id() ) {
    $db->add_device(); exit;
  }

  $db->update_device();

  list($mb_limit, $mb_used) = $db->get_data_usage();

  if( $mb_limit > $mb_used ) {
    $ipt = new Iptables($ip);
    $ipt->add_client();
  }
}

exit;
